{
  "type": "record",
  "name": "Document",
  "namespace": "benchmark.v2",
  "fields": [
    {"name": "id", "type": "string", "default": ""},
    {"name": "status", "type": "int", "default": 0},
    {"name": "meta", "type": ["null", {
      "type": "record",
      "name": "DocumentMeta",
      "fields": [
        {"name": "region", "type": "string", "default": ""},
        {"name": "version", "type": "int", "default": 0}
      ]
    }], "default": null},
    {"name": "items", "type": {"type": "array", "items": {
      "type": "record",
      "name": "DocumentItem",
      "fields": [
        {"name": "sku", "type": "string", "default": ""},
        {"name": "qty", "type": "int", "default": 0},
        {"name": "price_minor", "type": "long", "default": 0}
      ]
    }}, "default": []}
  ]
}
